
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 5.7
  - hhvm

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script: phpunit --coverage-text

matrix:
  fast_finish: true
